<script setup>
import { ref } from 'vue'
const sent = ref(false)
</script>
<template>
  <section class="contact-page"><div class="contact-heading"><p class="eyebrow">Say hello</p><h1>Let's make<br /><em>something good.</em></h1><p>Questions, wholesale, collaborations, or just want to say hi? We would love to hear from you.</p></div><div class="contact-layout"><form @submit.prevent="sent = true"><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@email.com" /></label><label>Message<textarea required rows="4" placeholder="Tell us a little more..."></textarea></label><button class="primary-btn" type="submit">{{ sent ? 'Message sent ✓' : 'Send message' }} <span>↗</span></button></form><div class="contact-info"><div><span>General enquiries</span><a href="mailto:hello@onda.co">hello@onda.co</a></div><div><span>Wholesale & partnerships</span><a href="mailto:studio@onda.co">studio@onda.co</a></div><div><span>Based in</span><p>Melbourne, Australia<br />Shipping everywhere</p></div></div></div></section>
</template>
<style scoped>
.contact-page { max-width: 1040px; margin: auto; padding: 70px 30px 20px; }.contact-heading { text-align: center; }.contact-heading h1 { font: 600 clamp(55px, 7vw, 88px)/.95 'Playfair Display', serif; letter-spacing: -.06em; margin: 20px 0; }.contact-heading > p:last-child { color: var(--muted); max-width: 400px; margin: auto; line-height: 1.7; font-size: 14px; }.contact-layout { display: grid; grid-template-columns: 1.2fr .8fr; gap: 100px; margin-top: 75px; }form { display: grid; gap: 25px; }label { color: var(--muted); font-size: 12px; display: grid; gap: 8px; }input, textarea { border: 0; border-bottom: 1px solid var(--line); background: transparent; padding: 8px 0; color: var(--ink); outline: none; resize: vertical; }input:focus, textarea:focus { border-color: var(--ink); }.primary-btn { justify-self: start; margin-top: 5px; }.contact-info { border-left: 1px solid var(--line); padding-left: 35px; display: grid; align-content: start; gap: 35px; }.contact-info div { display: grid; gap: 9px; }.contact-info span { color: var(--muted); text-transform: uppercase; letter-spacing: .12em; font-size: 9px; }.contact-info a, .contact-info p { font: 500 18px 'Playfair Display', serif; line-height: 1.5; }@media (max-width: 700px) { .contact-page { padding: 45px 20px; }.contact-layout { grid-template-columns: 1fr; gap: 55px; margin-top: 55px; }.contact-info { border-left: 0; border-top: 1px solid var(--line); padding: 35px 0 0; } }
</style>
