<template>
  <section class="gallery-page"><div class="gallery-heading"><p class="eyebrow">The collection</p><h1>Made for your<br /><em>every day.</em></h1><p>Three sizes. One considered silhouette. Find the bottle that fits your rhythm.</p></div><div class="gallery-grid"><article v-for="(item, index) in products" :key="item.name" :class="`tone-${index + 1}`"><div class="gallery-bottle"><i></i><span>{{ item.label }}</span></div><div class="product-meta"><h2>{{ item.name }}</h2><span>{{ item.size }} · ${{ item.price }}</span></div></article></div></section>
</template>
<script setup>
const products = [{ name: 'The Daily', label: '01', size: '500 ml', price: '48' }, { name: 'The Wanderer', label: '02', size: '750 ml', price: '56' }, { name: 'The Little One', label: '03', size: '300 ml', price: '38' }]
</script>
<style scoped>
.gallery-page { max-width: 1040px; margin: auto; padding: 70px 30px 20px; }.gallery-heading { display: flex; align-items: end; justify-content: space-between; gap: 35px; margin-bottom: 65px; }.gallery-heading h1 { font: 600 clamp(55px, 7vw, 88px)/.95 'Playfair Display', serif; letter-spacing: -.06em; margin-top: 20px; }.gallery-heading > p:last-child { max-width: 235px; color: var(--muted); line-height: 1.7; font-size: 13px; margin-bottom: 6px; }.gallery-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }.gallery-grid article { padding: 23px; background: #e2e7dc; }.gallery-grid article:nth-child(2) { background: #f2dfc5; }.gallery-grid article:nth-child(3) { background: #e7d7d1; }.gallery-bottle { height: 340px; display: grid; place-items: center; position: relative; }.gallery-bottle:before { content: ''; width: 125px; height: 268px; border-radius: 38px 38px 27px 27px; background: #b66344; box-shadow: 16px 20px 25px #596c5833; transform: rotate(5deg); }.tone-2 .gallery-bottle:before { background: #b2a081; transform: rotate(-4deg); }.tone-3 .gallery-bottle:before { background: #7b9386; transform: rotate(4deg); }.gallery-bottle i { position: absolute; top: 39px; width: 48px; height: 34px; border-radius: 7px 7px 2px 2px; background: #bea476; z-index: 1; }.gallery-bottle span { position: absolute; z-index: 1; font: 600 26px 'Playfair Display', serif; color: #f9dfca; }.product-meta { border-top: 1px solid #15231f44; padding-top: 14px; display: flex; justify-content: space-between; align-items: baseline; }.product-meta h2 { font: 500 21px 'Playfair Display', serif; }.product-meta span { color: var(--muted); font-size: 11px; } @media (max-width: 700px) { .gallery-page { padding: 45px 20px; }.gallery-heading { display: block; }.gallery-heading > p:last-child { margin-top: 25px; }.gallery-grid { grid-template-columns: 1fr; }.gallery-bottle { height: 280px; } }
</style>
